In [1]:
import pandas as pd
import numpy as np
import matplotlib as mtb

# dataframe 기본
row ,column으로 이뤄진 2차원 배열 

dataframe =[],[]

|메뉴|가격|판매량|
|---|----|---|
|아메리카노|2500|30|
|라떼|3000|20|

In [5]:
data ={
        '메뉴' : ['아메리카노','라떼'],
        '가격' : [2500, 3000],
        '판매량': [30,20]
}

df= pd.DataFrame(data)
df

      메뉴    가격  판매량
0  아메리카노  2500   30
1     라떼  3000   20

In [7]:
type(df)

pandas.DataFrame

In [8]:
s=  pd.Series([1,2,3,4])
df = pd.DataFrame({'value' : [1,2,3,4,]})

print(s.ndim)
print(df.ndim)

1
2

i

In [9]:
data = { 
        'tracking_no ': ['T10001', 'T10002', 'T10003'],
        'destination' : ['서울', '대전','부산'],
        'weight_kg' : [2.4, 5.1, 1.8],
        'delivered' : [True, False, True]


}

In [12]:
delivers = pd.DataFrame(data)
delivers

  tracking_no  destination  weight_kg  delivered
0       T10001          서울        2.4       True
1       T10002          대전        5.1      False
2       T10003          부산        1.8       True

In [ ]:
delivers.loc[0]    #행 뽑아오기

tracking_no     T10001
destination         서울
weight_kg          2.4
delivered         True
Name: 0, dtype: object

In [ ]:
delivers['delivered']   #열 뽑아오기

0     True
1    False
2     True
Name: delivered, dtype: bool

In [22]:
delivers.shape

(3, 4)

In [26]:
row_count  = delivers.shape[0]
print(f'행의 갯수  = {row_count}')

column_count = delivers.shape[1]
print(f'열의 갯수  = {column_count}')

행의 갯수  = 3
열의 갯수  = 4

In [36]:
data = {
        'product' : ['pc', 'keyboard', 'mouse'],
        'quantity' : [1,2,3],
        'unit_price': [3000000, 120000, 100000]
}

product = pd.DataFrame(data, index=['p001','q001','u001'])


print(product.index[1:])    #인덱스 번호 확인  
print(product.columns)  #시리즈의 인덱스 가져오기 

product

Index(['q001', 'u001'], dtype='str')
Index(['product', 'quantity', 'unit_price'], dtype='str')

       product  quantity  unit_price
p001        pc         1     3000000
q001  keyboard         2      120000
u001     mouse         3      100000

In [41]:
product = pd.Series(['pc','keyboard','mouse'])
quantify = pd.Series([1,2,3,])
unit_price = pd.Series([3000000,120000,100000]
)

df = pd.DataFrame([product,quantify,unit_price])

df

         0         1       2
0       pc  keyboard   mouse
1        1         2       3
2  3000000    120000  100000

In [42]:
data = { 
        'product' : product,
        'quantify': quantify,
        'unit_price': unit_price

}
df = pd.DataFrame(data)

df

    product  quantify  unit_price
0        pc         1     3000000
1  keyboard         2      120000
2     mouse         3      100000

In [43]:
(quantify) * (unit_price)

0    3000000
1     240000
2     300000
dtype: int64

In [46]:
df['quantify'] * df['unit_price']

0    3000000
1     240000
2     300000
dtype: int64

In [ ]:
df[['quantify','unit_price']]   # 배열이 아닌 문자열 = 시리즈
                                #하나를 가져오는데 시리즈가 아닌 데이터프레임 원할 때
                                #[ [] ]사용

   quantify  unit_price
0         1     3000000
1         2      120000
2         3      100000

In [50]:
df.dtypes

product         str
quantify      int64
unit_price    int64
dtype: object

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product     3 non-null      str
 1   quantify    3 non-null      int64
 2   unit_price  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [52]:
df.T

                  0         1       2
product          pc  keyboard   mouse
quantify          1         2       3
unit_price  3000000    120000  100000

In [72]:
import pandas as pd
import numpy as np

orders = pd.DataFrame(
    {
        "order_date": pd.to_datetime([
            "2026-08-01", "2026-08-01", "2026-08-02", "2026-08-03",
            "2026-08-04", "2026-08-05", "2026-08-05", "2026-08-06",
            "2026-08-07", "2026-08-08", "2026-08-09", "2026-08-10",
        ]),
        "customer": pd.Series(
            ["민준", "서연", "지우", "도윤", "하준", "서연",
             "민준", "지우", "도윤", "하준", "민준", "서연"],
            dtype="string",
        ),
        "region": pd.Series(
            ["서울", "부산", "서울", "대전", "부산", "서울",
             "대전", "서울", "부산", "대전", "서울", "부산"],
            dtype="category",
        ),
        "product": pd.Series(
            ["키보드", "모니터", "마우스", "키보드", "모니터", "키보드",
             "마우스", "모니터", "키보드", "마우스", "모니터", "키보드"],
            dtype="category",
        ),
        "quantity": pd.Series(
            [2, 1, 3, 2, 1, 4, 2, 1, 5, 2, 1, 3],
            dtype="Int64",
        ),
        "unit_price": [
            45000, 320000, 25000, 45000, 320000, 45000,
            25000, 320000, 45000, 25000, 320000, 45000,
        ],
        "discount_rate": [
            0.00, 0.10, np.nan, 0.05, 0.00, 0.10,
            0.00, np.nan, 0.05, 0.00, 0.10, 0.00,
        ],
        "paid": pd.Series(
            [True, True, False, True, True, True,
             False, True, True, pd.NA, True, False],
            dtype="boolean",
        ),
    },
    index=pd.Index(
        [f"O{i:03d}" for i in range(1, 13)],
        name="order_id",
    ),
)

orders["customer"] = pd.array(
    ["민준", "서연", "지우", "도윤", "하준", "서연",
     "민준", "지우", "도윤", "하준", "민준", "서연"],
    dtype="string",
)
orders["region"] = pd.Categorical(
    ["서울", "부산", "서울", "대전", "부산", "서울",
     "대전", "서울", "부산", "대전", "서울", "부산"]
)
orders["product"] = pd.Categorical(
    ["키보드", "모니터", "마우스", "키보드", "모니터", "키보드",
     "마우스", "모니터", "키보드", "마우스", "모니터", "키보드"]
)
orders["quantity"] = pd.array(
    [2, 1, 3, 2, 1, 4, 2, 1, 5, 2, 1, 3],
    dtype="Int64",
)
orders["paid"] = pd.array(
    [True, True, False, True, True, True,
     False, True, True, pd.NA, True, False],
    dtype="boolean",
)

print(orders)

         order_date customer region product  quantity  unit_price  \
order_id
O001     2026-08-01       민준     서울     키보드         2       45000
O002     2026-08-01       서연     부산     모니터         1      320000
O003     2026-08-02       지우     서울     마우스         3       25000
O004     2026-08-03       도윤     대전     키보드         2       45000
O005     2026-08-04       하준     부산     모니터         1      320000
O006     2026-08-05       서연     서울     키보드         4       45000
O007     2026-08-05       민준     대전     마우스         2       25000
O008     2026-08-06       지우     서울     모니터         1      320000
O009     2026-08-07       도윤     부산     키보드         5       45000
O010     2026-08-08       하준     대전     마우스         2       25000
O011     2026-08-09       민준     서울     모니터         1      320000
O012     2026-08-10       서연     부산     키보드         3       45000

          discount_rate   paid
order_id
O001               0.00   True
O002               0.10   True
O003                NaN  False
O004               0.05   True
O005               0.00   True
O006               0.10   True
O007               0.00  False
O008                NaN   True
O009               0.05   True
O010               0.00   <NA>
O011               0.10   True
O012               0.00  False

In [ ]:
orders.head() #머리부터
orders.tail() #꼬리부터

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O001,2026-08-01,민준,서울,키보드,2,45000,0.00,True
O002,2026-08-01,서연,부산,모니터,1,320000,0.10,True
O003,2026-08-02,지우,서울,마우스,3,25000,NaN,False
O004,2026-08-03,도윤,대전,키보드,2,45000,0.05,True
O005,2026-08-04,하준,부산,모니터,1,320000,0.00,True

In [65]:
orders.tail(10)

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O003,2026-08-02,지우,서울,마우스,3,25000,NaN,False
O004,2026-08-03,도윤,대전,키보드,2,45000,0.05,True
O005,2026-08-04,하준,부산,모니터,1,320000,0.00,True
O006,2026-08-05,서연,서울,키보드,4,45000,0.10,True
O007,2026-08-05,민준,대전,마우스,2,25000,0.00,False
O008,2026-08-06,지우,서울,모니터,1,320000,NaN,True
O009,2026-08-07,도윤,부산,키보드,5,45000,0.05,True
O010,2026-08-08,하준,대전,마우스,2,25000,0.00,<NA>
O011,2026-08-09,민준,서울,모니터,1,320000,0.10,True
O012,2026-08-10,서연,부산,키보드,3,45000,0.00,False

In [66]:
orders.sample()

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O002,2026-08-01,서연,부산,모니터,1,320000,0.1,True

In [ ]:
orders.sample(2, random_state=42) #42개 중 랜덤 2개  //  표본조사 sample

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O011,2026-08-09,민준,서울,모니터,1,320000,0.1,True
O010,2026-08-08,하준,대전,마우스,2,25000,0.0,<NA>

In [75]:
orders.sample(frac=0.25)

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O008,2026-08-06,지우,서울,모니터,1,320000,NaN,True
O005,2026-08-04,하준,부산,모니터,1,320000,0.0,True
O002,2026-08-01,서연,부산,모니터,1,320000,0.1,True

In [76]:
orders.describe()

                order_date  quantity     unit_price  discount_rate
count                   12      12.0      12.000000      10.000000
mean   2026-08-05 02:00:00      2.25  131666.666667       0.040000
min    2026-08-01 00:00:00       1.0   25000.000000       0.000000
25%    2026-08-02 18:00:00       1.0   40000.000000       0.000000
50%    2026-08-05 00:00:00       2.0   45000.000000       0.025000
75%    2026-08-07 06:00:00       3.0  320000.000000       0.087500
max    2026-08-10 00:00:00       5.0  320000.000000       0.100000
std                    NaN  1.288057  139338.262926       0.045947

In [79]:
orders[['quantity','unit_price','discount_rate']].describe()

       quantity     unit_price  discount_rate
count      12.0      12.000000      10.000000
mean       2.25  131666.666667       0.040000
std    1.288057  139338.262926       0.045947
min         1.0   25000.000000       0.000000
25%         1.0   40000.000000       0.000000
50%         2.0   45000.000000       0.025000
75%         3.0  320000.000000       0.087500
max         5.0  320000.000000       0.100000