In [3]:
import pandas as pd
import numpy as np

In [28]:
IRIS_CSV_PATH = 'iris.csv'
IRIS_COLUMNS = ['sepal_length', 'sepal_width','petal_length','petal_width','species']
#길이 넓이 종 네임지정

In [9]:
pd.read_csv('iris.csv')

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[150 rows x 5 columns]

In [29]:
df = pd.read_csv(
            'iris.csv',
            skiprows =1,
            header = None,
            names = IRIS_COLUMNS   #
            
        )   #1행 버리기


df.shape

(150, 5)

In [33]:
df.sample(n=10)

     sepal_length  sepal_width  petal_length  petal_width  species
105           7.6          3.0           6.6          2.1        2
78            6.0          2.9           4.5          1.5        1
52            6.9          3.1           4.9          1.5        1
148           6.2          3.4           5.4          2.3        2
107           7.3          2.9           6.3          1.8        2
47            4.6          3.2           1.4          0.2        0
34            4.9          3.1           1.5          0.2        0
76            6.8          2.8           4.8          1.4        1
120           6.9          3.2           5.7          2.3        2
73            6.1          2.8           4.7          1.2        1

In [35]:
df.isna().sum()  #결측값 확인

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [38]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width     species
count    150.000000   150.000000    150.000000   150.000000  150.000000
mean       5.843333     3.057333      3.758000     1.199333    1.000000
std        0.828066     0.435866      1.765298     0.762238    0.819232
min        4.300000     2.000000      1.000000     0.100000    0.000000
25%        5.100000     2.800000      1.600000     0.300000    0.000000
50%        5.800000     3.000000      4.350000     1.300000    1.000000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

## 기술통계에서 살펴보는 데이터와 목적

- 중심경향치 (데이터가 어디에 모여있는가)
  - 평균(mean) : 모든 값을 더한뒤 갯수로 나눈값
  - 중앙값(midian) : 크기 순서대로 나열했을 때 정 중앙에 있는 값
  - 최빈값(mode) : 데이터에서 가장 자주 등장하는 값 
  

- 산포도(데이터가 어떻게 퍼져있는지)
  - 분산(variance) : 평균에서 데이터가 떨어진 정도를 제곱해서 구한 평균 
  - 표준편차(standard deviation) : 분산 양의 제곱 근 sqrt(p) #std
  - 사분위수(quartile) : 전체 데이터를 4등분한 위치의 값 


- 분포의 형태(데이터의 모양)
  - 왜도 : 분포가 한쪽으로 치우쳐진 정도 
  - 첨도 : 분포의 뾰족한 정도

In [40]:
df['sepal_width'].median()  #중앙 값 보기

np.float64(3.0)

In [43]:

#setosa,versicolor,virginica
species_map = {        #매핑  / #파생변수
    0 : 'setosa',
    1 : 'versicolor',
    2 : 'virginica'
}

species_df = df.copy()

species_df

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [44]:
df['species'].map(species_map)  #

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: str

In [45]:
species_df['species_code'] = species_df['species'].map(species_map)

In [46]:
species_df.head()

   sepal_length  sepal_width  petal_length  petal_width  species species_code
0           5.1          3.5           1.4          0.2        0       setosa
1           4.9          3.0           1.4          0.2        0       setosa
2           4.7          3.2           1.3          0.2        0       setosa
3           4.6          3.1           1.5          0.2        0       setosa
4           5.0          3.6           1.4          0.2        0       setosa

In [47]:
species_df['species'].unique()

array([0, 1, 2])

In [49]:
species_df['species'].value_counts()

species_df['species'].value_counts(normalize = True)  #%로 보는 방법

species
0    0.333333
1    0.333333
2    0.333333
Name: proportion, dtype: float64

In [52]:
df_ng = df.head().copy()
df_ng['sepal_length'] =df_ng['sepal_length'].astype('str')
df_ng.loc[2, 'sepal_length'] = 'unknown'

df_ng

  sepal_length  sepal_width  petal_length  petal_width  species
0          5.1          3.5           1.4          0.2        0
1          4.9          3.0           1.4          0.2        0
2      unknown          3.2           1.3          0.2        0
3          4.6          3.1           1.5          0.2        0
4          5.0          3.6           1.4          0.2        0

## 데이터 탐색 목적 
데이터 탐색 과정에서 다음과 같은 질문에 대한 대답을 한다
- 데이터는 몇 행 / 몇 열인가?
- 어떤 컬럼이 존재하는가?
- 각 컬럼은 어떤 타입인가?
- 데이터의 앞부분과 뒷부분은 어떻게 생겼는가?
- 결측값은 존재하는가?
- 수치 데이터의 범위는 어느정도인가?
- 범주에는 어떤 값들이 존재하는가?
- 각 범주는 몇번 등장하는가?