In [3]:
import pandas as pd
import numpy as np

In [28]:
IRIS_CSV_PATH = 'iris.csv'
IRIS_COLUMNS = ['sepal_length', 'sepal_width','petal_length','petal_width','species']
#길이 넓이 종 네임지정

In [9]:
pd.read_csv('iris.csv')

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[150 rows x 5 columns]

In [ ]:
df = pd.read_csv(
            'iris.csv',
            skiprows =1,
            header = None,
            names =IRIS_COLUMNS   #
            
        )   #1행 버리기


df.shape

(150, 5)

In [18]:
df

       0    1    2    3  4
0    5.1  3.5  1.4  0.2  0
1    4.9  3.0  1.4  0.2  0
2    4.7  3.2  1.3  0.2  0
3    4.6  3.1  1.5  0.2  0
4    5.0  3.6  1.4  0.2  0
..   ...  ...  ...  ... ..
145  6.7  3.0  5.2  2.3  2
146  6.3  2.5  5.0  1.9  2
147  6.5  3.0  5.2  2.0  2
148  6.2  3.4  5.4  2.3  2
149  5.9  3.0  5.1  1.8  2

[150 rows x 5 columns]